create table ANKEN_RIREKI (
    ANKEN_RIREKI_ID int not null auto_increment,
    ANKEN_RIREKI_NO int not null,
    ANKEN_ID int not null,
    NENDO int not null,
    KOKYAKU_NAME varchar(10) not null,
    KOKYAKU_INITIAL varchar(1) not null,
    ANKEN_NAME varchar(100) not null,
    JUTYU_NAME varchar(100),
    KAIHATSU_GROUP_HEAD varchar(10),
    EIGYO varchar(10) not null,
    HATTYU_TYPE_CODE int,
    HATTYU_MIKOMI_DATE varchar(10) not null,
    HATTYU_DATE varchar(10),
    KENSYU_DATE varchar(10),
    KAKUDO_CODE int not null,
    JUTYUGAKU decimal(14,0) not null,
    NOTES varchar(1000),
    UK_YOKUYOKU decimal(14,0),
    UK_CONDITION_CODE int not null,
    INSERT_DATE timestamp not null,
    INSERT_EMP_NO varchar(10) not null,
    constraint ANKEN_RIREKI_PK primary key(ANKEN_RIREKI_ID)
);
