create table MONTHLY_GENKA (
    MONTHLY_GENKA_ID int not null auto_increment,
    THEME_NO varchar(10),
    THEME_GROUP varchar(10) not null,
    NENDO int not null,
    MONTH int not null,
    GK_CONDITION_CODE int,
    K_ROUMUHI decimal(14,0),
    K_KOUSU decimal(5,1),
    K_TANKA decimal(14,0),
    K_GAITYU decimal(14,0),
    K_RYOHI decimal(14,0),
    K_SONOTA decimal(14,0),
    K_KEIHI decimal(14,0),
    K_SUM decimal(14,0),
    M_ROUMUHI decimal(14,0),
    M_KOUSU decimal(5,1),
    M_TANKA decimal(14,0),
    M_GAITYU decimal(14,0),
    M_RYOHI decimal(14,0),
    M_SONOTA decimal(14,0),
    M_KEIHI decimal(14,0),
    M_SUM decimal(14,0),
    J_ROUMUHI decimal(14,0),
    J_KOUSU decimal(5,1),
    J_TANKA decimal(14,0),
    J_GAITYU decimal(14,0),
    J_RYOHI decimal(14,0),
    J_SONOTA decimal(14,0),
    J_KEIHI decimal(14,0),
    J_SUM decimal(14,0),
    K_M_GAP decimal(14,0),
    K_J_GAP decimal(14,0),
    ARARI decimal(14,0),
    ARARI_PAR decimal(14,0),
    AVERAGE_TANKA decimal(14,0),
    constraint MONTHLY_GENKA_PK primary key(MONTHLY_GENKA_ID)
);
