create table URIAGE_KEIKAKU (
    ANKEN_RIREKI_ID int not null,
    NENDO int not null,
    UK_APR decimal(14,0),
    UK_MAY decimal(14,0),
    UK_JUN decimal(14,0),
    UK_JUL decimal(14,0),
    UK_AUG decimal(14,0),
    UK_SEP decimal(14,0),
    UK_OCT decimal(14,0),
    UK_NOV decimal(14,0),
    UK_DEC decimal(14,0),
    UK_JAN decimal(14,0),
    UK_FEB decimal(14,0),
    UK_MAR decimal(14,0),
    UK_KAMIKI decimal(14,0),
    UK_SHIMOKI decimal(14,0),
    UK_TOTAL decimal(14,0),
    constraint URIAGE_KEIKAKU_PK primary key(ANKEN_RIREKI_ID, NENDO)
);
